import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link.js";

import { getAllFilesMetaData } from "../../lib/mdx.js";
import Navbar from "../../components/Navbar/Navbar.js";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Blog Jam Stack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        {posts.map((post) => (
          <>
            <Link
              key={post.slug}
              href={`/${post.slug}`}
              className={styles.card}
            >
              <h2>{post.title}</h2>
              <p>{post.date}</p>
            </Link>
          </>
        ))}
      </div>
    </>
  );
}

export async function getStaticProps() {
  const posts = await getAllFilesMetaData();
  console.log(posts);

  return {
    props: { posts },
  };
}
